# Form implementation generated from reading ui file 'ui/animations.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pageAnimations(object):
    def setupUi(self, pageAnimations):
        pageAnimations.setObjectName("pageAnimations")
        pageAnimations.resize(995, 661)
        self.horizontalLayout = QtWidgets.QHBoxLayout(pageAnimations)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lvAnimations = QtWidgets.QListView(parent=pageAnimations)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvAnimations.sizePolicy().hasHeightForWidth())
        self.lvAnimations.setSizePolicy(sizePolicy)
        self.lvAnimations.setObjectName("lvAnimations")
        self.verticalLayout.addWidget(self.lvAnimations)
        self.btnNewAnimation = QtWidgets.QPushButton(parent=pageAnimations)
        self.btnNewAnimation.setObjectName("btnNewAnimation")
        self.verticalLayout.addWidget(self.btnNewAnimation)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.groupBox = QtWidgets.QGroupBox(parent=pageAnimations)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.tbTexture = QtWidgets.QLineEdit(parent=self.groupBox)
        self.tbTexture.setObjectName("tbTexture")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tbTexture)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sbGlobalOriginX = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.sbGlobalOriginX.setMinimum(-1024.0)
        self.sbGlobalOriginX.setMaximum(1024.0)
        self.sbGlobalOriginX.setObjectName("sbGlobalOriginX")
        self.horizontalLayout_2.addWidget(self.sbGlobalOriginX)
        self.sbGlobalOriginY = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.sbGlobalOriginY.setMinimum(-1024.0)
        self.sbGlobalOriginY.setMaximum(1024.0)
        self.sbGlobalOriginY.setObjectName("sbGlobalOriginY")
        self.horizontalLayout_2.addWidget(self.sbGlobalOriginY)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lvClips = QtWidgets.QListView(parent=self.groupBox)
        self.lvClips.setObjectName("lvClips")
        self.verticalLayout_2.addWidget(self.lvClips)
        self.btnNewClip = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnNewClip.setObjectName("btnNewClip")
        self.verticalLayout_2.addWidget(self.btnNewClip)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(pageAnimations)
        QtCore.QMetaObject.connectSlotsByName(pageAnimations)

    def retranslateUi(self, pageAnimations):
        _translate = QtCore.QCoreApplication.translate
        pageAnimations.setWindowTitle(_translate("pageAnimations", "Form"))
        self.btnNewAnimation.setText(_translate("pageAnimations", "New Animation"))
        self.label.setText(_translate("pageAnimations", "Texture"))
        self.label_2.setText(_translate("pageAnimations", "Global Origin"))
        self.label_3.setText(_translate("pageAnimations", "Clips"))
        self.btnNewClip.setText(_translate("pageAnimations", "New Clip"))
