# Form implementation generated from reading ui file 'ui/editorSettingsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_editorSettingsDialog(object):
    def setupUi(self, editorSettingsDialog):
        editorSettingsDialog.setObjectName("editorSettingsDialog")
        editorSettingsDialog.resize(361, 174)
        self.formLayout = QtWidgets.QFormLayout(editorSettingsDialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=editorSettingsDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.sbGridWidth = QtWidgets.QSpinBox(parent=editorSettingsDialog)
        self.sbGridWidth.setMaximum(250)
        self.sbGridWidth.setProperty("value", 8)
        self.sbGridWidth.setObjectName("sbGridWidth")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sbGridWidth)
        self.label_2 = QtWidgets.QLabel(parent=editorSettingsDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.sbGridHeight = QtWidgets.QSpinBox(parent=editorSettingsDialog)
        self.sbGridHeight.setMaximum(250)
        self.sbGridHeight.setProperty("value", 8)
        self.sbGridHeight.setObjectName("sbGridHeight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sbGridHeight)
        self.label_3 = QtWidgets.QLabel(parent=editorSettingsDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.cbShowGrid = QtWidgets.QCheckBox(parent=editorSettingsDialog)
        self.cbShowGrid.setText("")
        self.cbShowGrid.setChecked(True)
        self.cbShowGrid.setObjectName("cbShowGrid")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cbShowGrid)
        self.label_4 = QtWidgets.QLabel(parent=editorSettingsDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.cbSnapGrid = QtWidgets.QCheckBox(parent=editorSettingsDialog)
        self.cbSnapGrid.setText("")
        self.cbSnapGrid.setChecked(True)
        self.cbSnapGrid.setObjectName("cbSnapGrid")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cbSnapGrid)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=editorSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.buttonBox)

        self.retranslateUi(editorSettingsDialog)
        self.buttonBox.accepted.connect(editorSettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(editorSettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(editorSettingsDialog)

    def retranslateUi(self, editorSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        editorSettingsDialog.setWindowTitle(_translate("editorSettingsDialog", "Dialog"))
        self.label.setText(_translate("editorSettingsDialog", "Grid Width"))
        self.label_2.setText(_translate("editorSettingsDialog", "Grid Height"))
        self.label_3.setText(_translate("editorSettingsDialog", "Show Grid"))
        self.label_4.setText(_translate("editorSettingsDialog", "Snap to Grid"))
