# Form implementation generated from reading ui file 'ui/gamesettings.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pageGameSettings(object):
    def setupUi(self, pageGameSettings):
        pageGameSettings.setObjectName("pageGameSettings")
        pageGameSettings.resize(1539, 806)
        self.formLayout = QtWidgets.QFormLayout(pageGameSettings)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(parent=pageGameSettings)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.sbMaxLives = QtWidgets.QSpinBox(parent=pageGameSettings)
        self.sbMaxLives.setObjectName("sbMaxLives")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sbMaxLives)
        self.label_5 = QtWidgets.QLabel(parent=pageGameSettings)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.sbMaxHealth = QtWidgets.QSpinBox(parent=pageGameSettings)
        self.sbMaxHealth.setObjectName("sbMaxHealth")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sbMaxHealth)
        self.label = QtWidgets.QLabel(parent=pageGameSettings)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnAddLevel = QtWidgets.QPushButton(parent=pageGameSettings)
        self.btnAddLevel.setText("")
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.ListAdd)
        self.btnAddLevel.setIcon(icon)
        self.btnAddLevel.setObjectName("btnAddLevel")
        self.verticalLayout_2.addWidget(self.btnAddLevel)
        self.btnRemoveLevel = QtWidgets.QPushButton(parent=pageGameSettings)
        self.btnRemoveLevel.setText("")
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.ListRemove)
        self.btnRemoveLevel.setIcon(icon)
        self.btnRemoveLevel.setObjectName("btnRemoveLevel")
        self.verticalLayout_2.addWidget(self.btnRemoveLevel)
        self.btnMoveLevelUp = QtWidgets.QPushButton(parent=pageGameSettings)
        self.btnMoveLevelUp.setText("")
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.GoUp)
        self.btnMoveLevelUp.setIcon(icon)
        self.btnMoveLevelUp.setObjectName("btnMoveLevelUp")
        self.verticalLayout_2.addWidget(self.btnMoveLevelUp)
        self.btnMoveLevelDown = QtWidgets.QPushButton(parent=pageGameSettings)
        self.btnMoveLevelDown.setText("")
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.GoDown)
        self.btnMoveLevelDown.setIcon(icon)
        self.btnMoveLevelDown.setObjectName("btnMoveLevelDown")
        self.verticalLayout_2.addWidget(self.btnMoveLevelDown)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.lvLevelPlaylist = QtWidgets.QListView(parent=pageGameSettings)
        self.lvLevelPlaylist.setObjectName("lvLevelPlaylist")
        self.horizontalLayout_2.addWidget(self.lvLevelPlaylist)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_2)

        self.retranslateUi(pageGameSettings)
        QtCore.QMetaObject.connectSlotsByName(pageGameSettings)

    def retranslateUi(self, pageGameSettings):
        _translate = QtCore.QCoreApplication.translate
        pageGameSettings.setWindowTitle(_translate("pageGameSettings", "Form"))
        self.label_4.setText(_translate("pageGameSettings", "Max Lives"))
        self.label_5.setText(_translate("pageGameSettings", "Max Health"))
        self.label.setText(_translate("pageGameSettings", "Level Playlist"))
