# Form implementation generated from reading ui file 'ui/itemdialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_itemDialog(object):
    def setupUi(self, itemDialog):
        itemDialog.setObjectName("itemDialog")
        itemDialog.resize(400, 90)
        self.formLayout = QtWidgets.QFormLayout(itemDialog)
        self.formLayout.setObjectName("formLayout")
        self.lblName = QtWidgets.QLabel(parent=itemDialog)
        self.lblName.setObjectName("lblName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblName)
        self.tbName = QtWidgets.QLineEdit(parent=itemDialog)
        self.tbName.setObjectName("tbName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tbName)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=itemDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.buttonBox)

        self.retranslateUi(itemDialog)
        self.buttonBox.accepted.connect(itemDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(itemDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(itemDialog)

    def retranslateUi(self, itemDialog):
        _translate = QtCore.QCoreApplication.translate
        itemDialog.setWindowTitle(_translate("itemDialog", "Add New..."))
        self.lblName.setText(_translate("itemDialog", "Name:"))
