# Form implementation generated from reading ui file 'ui/levels.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pageLevelEditor(object):
    def setupUi(self, pageLevelEditor):
        pageLevelEditor.setObjectName("pageLevelEditor")
        pageLevelEditor.resize(1149, 858)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(pageLevelEditor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lvLevels = QtWidgets.QListView(parent=pageLevelEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvLevels.sizePolicy().hasHeightForWidth())
        self.lvLevels.setSizePolicy(sizePolicy)
        self.lvLevels.setObjectName("lvLevels")
        self.verticalLayout.addWidget(self.lvLevels)
        self.btnNewLevel = QtWidgets.QPushButton(parent=pageLevelEditor)
        self.btnNewLevel.setObjectName("btnNewLevel")
        self.verticalLayout.addWidget(self.btnNewLevel)
        self.label = QtWidgets.QLabel(parent=pageLevelEditor)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lvEvents = QtWidgets.QListView(parent=pageLevelEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvEvents.sizePolicy().hasHeightForWidth())
        self.lvEvents.setSizePolicy(sizePolicy)
        self.lvEvents.setObjectName("lvEvents")
        self.verticalLayout.addWidget(self.lvEvents)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gvLevelEditor = LevelEditor(parent=pageLevelEditor)
        self.gvLevelEditor.setObjectName("gvLevelEditor")
        self.verticalLayout_2.addWidget(self.gvLevelEditor)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLevelSettings = QtWidgets.QPushButton(parent=pageLevelEditor)
        self.btnLevelSettings.setObjectName("btnLevelSettings")
        self.horizontalLayout.addWidget(self.btnLevelSettings)
        self.btnEditorSettings = QtWidgets.QPushButton(parent=pageLevelEditor)
        self.btnEditorSettings.setObjectName("btnEditorSettings")
        self.horizontalLayout.addWidget(self.btnEditorSettings)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(pageLevelEditor)
        QtCore.QMetaObject.connectSlotsByName(pageLevelEditor)

    def retranslateUi(self, pageLevelEditor):
        _translate = QtCore.QCoreApplication.translate
        pageLevelEditor.setWindowTitle(_translate("pageLevelEditor", "Form"))
        self.btnNewLevel.setText(_translate("pageLevelEditor", "New Level"))
        self.label.setText(_translate("pageLevelEditor", "Events:"))
        self.btnLevelSettings.setText(_translate("pageLevelEditor", "Level Settings"))
        self.btnEditorSettings.setText(_translate("pageLevelEditor", "Editor Settings"))
from widgets.leveleditor import LevelEditor
