# Form implementation generated from reading ui file 'ui/levelSettingsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_levelSettingsDialog(object):
    def setupUi(self, levelSettingsDialog):
        levelSettingsDialog.setObjectName("levelSettingsDialog")
        levelSettingsDialog.resize(511, 226)
        self.formLayout = QtWidgets.QFormLayout(levelSettingsDialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=levelSettingsDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=levelSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.buttonBox)
        self.label_2 = QtWidgets.QLabel(parent=levelSettingsDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.sbScrollSpeed = QtWidgets.QDoubleSpinBox(parent=levelSettingsDialog)
        self.sbScrollSpeed.setSingleStep(0.1)
        self.sbScrollSpeed.setObjectName("sbScrollSpeed")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sbScrollSpeed)
        self.cbInitialMusic = QtWidgets.QComboBox(parent=levelSettingsDialog)
        self.cbInitialMusic.setObjectName("cbInitialMusic")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cbInitialMusic)
        self.label_3 = QtWidgets.QLabel(parent=levelSettingsDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.groupBox = QtWidgets.QGroupBox(parent=levelSettingsDialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.sbStarfieldSpeed = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.sbStarfieldSpeed.setMaximum(10000.0)
        self.sbStarfieldSpeed.setSingleStep(0.01)
        self.sbStarfieldSpeed.setProperty("value", 0.08)
        self.sbStarfieldSpeed.setObjectName("sbStarfieldSpeed")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sbStarfieldSpeed)
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.cbStarfieldEnabled = QtWidgets.QCheckBox(parent=self.groupBox)
        self.cbStarfieldEnabled.setText("")
        self.cbStarfieldEnabled.setObjectName("cbStarfieldEnabled")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cbStarfieldEnabled)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.groupBox)

        self.retranslateUi(levelSettingsDialog)
        self.buttonBox.accepted.connect(levelSettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(levelSettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(levelSettingsDialog)

    def retranslateUi(self, levelSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        levelSettingsDialog.setWindowTitle(_translate("levelSettingsDialog", "Level settings"))
        self.label.setText(_translate("levelSettingsDialog", "Initial Music"))
        self.label_2.setText(_translate("levelSettingsDialog", "Scroll Speed"))
        self.label_3.setText(_translate("levelSettingsDialog", "Starfield"))
        self.label_4.setText(_translate("levelSettingsDialog", "Default Speed"))
        self.label_5.setText(_translate("levelSettingsDialog", "Enabled"))
