# Form implementation generated from reading ui file 'ui/levelSettingsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_levelSettingsDialog(object):
    def setupUi(self, levelSettingsDialog):
        levelSettingsDialog.setObjectName("levelSettingsDialog")
        levelSettingsDialog.resize(398, 122)
        self.formLayout = QtWidgets.QFormLayout(levelSettingsDialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=levelSettingsDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.tbInitialMusic = QtWidgets.QLineEdit(parent=levelSettingsDialog)
        self.tbInitialMusic.setObjectName("tbInitialMusic")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tbInitialMusic)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=levelSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.buttonBox)
        self.label_2 = QtWidgets.QLabel(parent=levelSettingsDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.sbScrollSpeed = QtWidgets.QDoubleSpinBox(parent=levelSettingsDialog)
        self.sbScrollSpeed.setSingleStep(0.1)
        self.sbScrollSpeed.setObjectName("sbScrollSpeed")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sbScrollSpeed)

        self.retranslateUi(levelSettingsDialog)
        self.buttonBox.accepted.connect(levelSettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(levelSettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(levelSettingsDialog)

    def retranslateUi(self, levelSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        levelSettingsDialog.setWindowTitle(_translate("levelSettingsDialog", "Level settings"))
        self.label.setText(_translate("levelSettingsDialog", "Initial Music"))
        self.label_2.setText(_translate("levelSettingsDialog", "Scroll Speed"))
