# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1319, 910)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabsPages = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabsPages.setObjectName("tabsPages")
        self.tabGameSettings = pageGameSettings()
        self.tabGameSettings.setObjectName("tabGameSettings")
        self.tabsPages.addTab(self.tabGameSettings, "")
        self.tabPlayer = pagePlayer()
        self.tabPlayer.setObjectName("tabPlayer")
        self.tabsPages.addTab(self.tabPlayer, "")
        self.tabProjectiles = pageProjectiles()
        self.tabProjectiles.setObjectName("tabProjectiles")
        self.tabsPages.addTab(self.tabProjectiles, "")
        self.tabWeaponsets = pageWeaponsets()
        self.tabWeaponsets.setObjectName("tabWeaponsets")
        self.tabsPages.addTab(self.tabWeaponsets, "")
        self.tabEnemies = pageEnemies()
        self.tabEnemies.setObjectName("tabEnemies")
        self.tabsPages.addTab(self.tabEnemies, "")
        self.tabScripts = pageScripts()
        self.tabScripts.setObjectName("tabScripts")
        self.tabsPages.addTab(self.tabScripts, "")
        self.tabCollectables = pageCollectables()
        self.tabCollectables.setObjectName("tabCollectables")
        self.tabsPages.addTab(self.tabCollectables, "")
        self.tabAnimations = pageAnimations()
        self.tabAnimations.setObjectName("tabAnimations")
        self.tabsPages.addTab(self.tabAnimations, "")
        self.tabLevelEditor = pageLevelEditor()
        self.tabLevelEditor.setObjectName("tabLevelEditor")
        self.tabsPages.addTab(self.tabLevelEditor, "")
        self.verticalLayout.addWidget(self.tabsPages)
        self.btnSave = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.btnSave)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1319, 30))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionPaths = QtGui.QAction(parent=MainWindow)
        self.actionPaths.setObjectName("actionPaths")
        self.menuSettings.addAction(self.actionPaths)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabsPages.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SPJ Def Editor"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.tabGameSettings), _translate("MainWindow", "Game Settings"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.tabPlayer), _translate("MainWindow", "Player"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.tabProjectiles), _translate("MainWindow", "Projectiles"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.tabWeaponsets), _translate("MainWindow", "Weapon Sets"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.tabEnemies), _translate("MainWindow", "Enemies"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.tabScripts), _translate("MainWindow", "Scripts"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.tabCollectables), _translate("MainWindow", "Collectables"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.tabAnimations), _translate("MainWindow", "Animations"))
        self.tabsPages.setTabText(self.tabsPages.indexOf(self.tabLevelEditor), _translate("MainWindow", "Levels"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionPaths.setText(_translate("MainWindow", "Paths"))
from pageanimations import pageAnimations
from pagecollectables import pageCollectables
from pageenemies import pageEnemies
from pagegamesettings import pageGameSettings
from pageleveleditor import pageLevelEditor
from pageplayer import pagePlayer
from pageprojectiles import pageProjectiles
from pagescripts import pageScripts
from pageweaponsets import pageWeaponsets
