# Form implementation generated from reading ui file 'ui/pathsdialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgPaths(object):
    def setupUi(self, dlgPaths):
        dlgPaths.setObjectName("dlgPaths")
        dlgPaths.resize(398, 88)
        dlgPaths.setModal(True)
        self.formLayout = QtWidgets.QFormLayout(dlgPaths)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=dlgPaths)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbPaths = QtWidgets.QLineEdit(parent=dlgPaths)
        self.tbPaths.setObjectName("tbPaths")
        self.horizontalLayout.addWidget(self.tbPaths)
        self.btnBrowse = QtWidgets.QPushButton(parent=dlgPaths)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout.addWidget(self.btnBrowse)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dlgPaths)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.buttonBox)

        self.retranslateUi(dlgPaths)
        self.buttonBox.accepted.connect(dlgPaths.accept) # type: ignore
        self.buttonBox.rejected.connect(dlgPaths.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgPaths)

    def retranslateUi(self, dlgPaths):
        _translate = QtCore.QCoreApplication.translate
        dlgPaths.setWindowTitle(_translate("dlgPaths", "Paths"))
        self.label.setText(_translate("dlgPaths", "Assets Path"))
        self.btnBrowse.setText(_translate("dlgPaths", "Browse"))
