# Form implementation generated from reading ui file 'ui/scripts.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pageScripts(object):
    def setupUi(self, pageScripts):
        pageScripts.setObjectName("pageScripts")
        pageScripts.resize(1178, 819)
        self.gridLayout = QtWidgets.QGridLayout(pageScripts)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lvScripts = QtWidgets.QListView(parent=pageScripts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvScripts.sizePolicy().hasHeightForWidth())
        self.lvScripts.setSizePolicy(sizePolicy)
        self.lvScripts.setObjectName("lvScripts")
        self.verticalLayout.addWidget(self.lvScripts)
        self.btnNewScript = QtWidgets.QPushButton(parent=pageScripts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewScript.sizePolicy().hasHeightForWidth())
        self.btnNewScript.setSizePolicy(sizePolicy)
        self.btnNewScript.setObjectName("btnNewScript")
        self.verticalLayout.addWidget(self.btnNewScript)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.stackedControls = QtWidgets.QStackedWidget(parent=pageScripts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedControls.sizePolicy().hasHeightForWidth())
        self.stackedControls.setSizePolicy(sizePolicy)
        self.stackedControls.setObjectName("stackedControls")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.stackedControls.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.teSource = LuaEditor(parent=self.groupBox)
        self.teSource.setObjectName("teSource")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.teSource)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        self.stackedControls.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedControls, 0, 1, 1, 1)

        self.retranslateUi(pageScripts)
        self.stackedControls.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(pageScripts)

    def retranslateUi(self, pageScripts):
        _translate = QtCore.QCoreApplication.translate
        pageScripts.setWindowTitle(_translate("pageScripts", "Form"))
        self.btnNewScript.setText(_translate("pageScripts", "New Script"))
        self.label.setText(_translate("pageScripts", "Select a script from the left"))
from widgets.luaeditor import LuaEditor
